# Generated by Django 4.0.5 on 2022-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
